### ISSUE TITLE
Add Earth engine features

### ISSUE THREAD

**Issue by benwulfe** [tnc-br/ddf_common#5]
We should be able to add earth engine sourced features to arbitrary csv files in a way similar to how we enrich the current code for load_sample_data.  We first load the main data with lat/lon and labels - then we take a list of earth engine assets that can return values at those lat/lon locations and add them as features.

**Comment by kazob1998** [comment]
in our insights and analytics solution we don't support GDrive ... we will need to tune the Hypothesis library to import isoscapes from Earth Engine
